services:
  nats:
    image: nats:2.10.9
    ports:
      - "4222:4222"
      - "8222:8222"
  agent-ts:
    build: ./ts
    depends_on:
      - nats
  agent-go:
    build: ./go
    depends_on:
      - nats
  agent-python:
    build: ./python
    depends_on:
      - nats
  simulator:
    build:
      context: ./tools
    depends_on:
      - nats
    stdin_open: true
    tty: true
    command: ["summarize.article", "This is a test message for the simulator"]